name: Branin Campaigns Smoke Test

on:
  push:
    branches:
      - copilot/fix-b407491a-3a77-40e0-a70b-35579e442c93
    paths:
      - 'scripts/branin_repeat_campaigns.py'
      - 'scripts/bo_benchmarks/**'
      - '.github/workflows/branin_campaigns_smoke_test.yaml'
  pull_request:
    paths:
      - 'scripts/branin_repeat_campaigns.py'
      - 'scripts/bo_benchmarks/**'
      - '.github/workflows/branin_campaigns_smoke_test.yaml'

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python and uv
        uses: ./.github/actions/setup
      
      - name: Install dependencies
        run: |
          uv sync
          uv pip install ax-platform torch gpcheck scikit-learn scipy imageio pillow matplotlib plotly
        env:
          PIP_TIMEOUT: 600
          PIP_RETRIES: 2
      
      - name: Run smoke test
        run: |
          cd scripts
          SMOKE_TEST=1 uv run python branin_repeat_campaigns.py
        env:
          SMOKE_TEST: "1"
      
      - name: Upload smoke test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-test-results
          path: |
            scripts/smoke_test_results/
          retention-days: 7
      
      - name: Upload smoke test logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-test-logs
          path: |
            scripts/branin_evaluation_logs/
          retention-days: 7
